# Generated by Django 5.2.2 on 2025-06-22 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_category_options_user_watchlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='has_bids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='number_of_bids',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
