# Generated by Django 5.2.2 on 2025-07-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listing_number_of_bids_alter_favorite_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='is_first_bid',
            field=models.BooleanField(default=False),
        ),
    ]
